lzc-sdk-version: "0.1"
name: Ryot
package: cloud.lazycat.app.ryot
version: 8.5.0
description: 一个用于追踪生活各方面的自托管平台
homepage: https://ryot.io
author: ryot
application:
  subdomain: ryot
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://ryot:8000/
services:
  ryot-db:
    image: docker.hlmirror.com/postgres:16-alpine
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    health_check:
       test:
          - CMD-SHELL
          - pg_isready -U postgres
       start_period: 60s
  ryot:
    image: docker.hlmirror.com/ignisda/ryot:v8
    environment:
      - TZ=Asia/Shanghai
      - SERVER_ADMIN_ACCESS_TOKEN=28ebb3ae554fa9867ba1
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
